<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net5.0;net6.0;net7.0;net8.0;net9.0;net10.0;netstandard2.1</TargetFrameworks>
		<Nullable>enable</Nullable>
		<LangVersion>12.0</LangVersion>

		<AssemblyName>$(AssemblyName)</AssemblyName>
		<RootNamespace>$(AssemblyName)</RootNamespace>
		<PackageId>$(AssemblyName)</PackageId>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageOutputPath>../nupkgs</PackageOutputPath>
		<Version>$(HubconSharedCoreVersion)</Version>
		<Authors>$(Authors)</Authors>
		<Company>$(Company)</Company>
		<Description>Shared core implementations for Hubcon.</Description>
		<RepositoryUrl>https://github.com/Brick-Logic/Hubcon</RepositoryUrl>
		<PackageTags>rpc;dotnet;high-performance;native-aot;tcp;http;websockets</PackageTags>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
		<Deterministic>True</Deterministic>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
		<Deterministic>True</Deterministic>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="[8.15.0, 9.0.0)" />
		<PackageReference Include="System.Threading.Channels" Version="[8.0.0, 11.0.0)" />
		<PackageReference Include="System.Text.Json" Version="[8.0.6, 11.0.0)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hubcon.Shared.Abstractions.Standard\Hubcon.Shared.Abstractions.Standard.csproj" />
		<ProjectReference Include="..\Hubcon.Shared.Abstractions\Hubcon.Shared.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)/../README.md" Pack="true" PackagePath="\" />
		<None Include="$(MSBuildThisFileDirectory)/../LICENSE" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
