namespace Hubcon.Shared.Core.Websockets
{
    public enum MessageType
    {
        connection_init,
        connection_ack,
        error,
        ack,
        operation_invoke,
        operation_response,
        ping,
        pong,
        subscription_init,
        subscription_data,
        subscription_data_with_ack,
        subscription_complete,
        ingest_init,
        ingest_init_ack,
        ingest_data,
        ingest_data_ack,
        ingest_complete,
        ingest_data_with_ack,
        operation_call,
        stream_init,
        stream_complete,
        stream_data_ack,
        stream_data,
        stream_data_with_ack,
        ingest_result,
        cancel
    }
}