using System.Collections.Generic;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using Hubcon.Analyzers.SourceGenerators.Models;
using HubconAnalyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateControllerPreservers
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<ControllerMetadata> pairs,
            string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine("using Hubcon;");
            sb.AppendLine("using Hubcon.Generated;");
            sb.AppendLine("using System.Runtime.CompilerServices;");

            foreach (var pair in pairs)
            {
                sb.AppendLine();
                sb.AppendLine($"namespace {pair.Controller.ContainingNamespace}");
                sb.AppendLine("{");
                var preserver = Execute(pair.Controller);
                sb.AppendLine(preserver);
                sb.AppendLine("}");
            }

            sb.AppendLine();

            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }

        public static string Execute(INamedTypeSymbol typeSymbol)
        {
            var sb = new StringBuilder();
            var preserverName = typeSymbol.Name;
            var ifaceFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var namespaceName = typeSymbol.ContainingNamespace?.ToDisplayString();
            var hasNamespace = !string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>";
            var baseIndent = hasNamespace ? "    " : "";
            var fullProxyName = hasNamespace ? $"{namespaceName}.{preserverName}" : preserverName;

            sb.AppendLine(
                $"{baseIndent}[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"{baseIndent}public static class {preserverName}PreserverModule");
            sb.AppendLine($"{baseIndent}{{");

            // Blindajes de metadata tradicionales contra el Trimmer
            sb.AppendLine(
                $"{baseIndent}    [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof({ifaceFullName}))]");
            sb.AppendLine(
                $"{baseIndent}    [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors, typeof({ifaceFullName}))]");
            sb.AppendLine(
                $"{baseIndent}    [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof(Microsoft.Extensions.Primitives.StringValues))]");

            sb.AppendLine(
                "        #if UNITY_2017_1_OR_NEWER\r\n        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\r\n        #else\r\n        [ModuleInitializer]\r\n        #endif");
            sb.AppendLine($"{baseIndent}    public static void Init()");
            sb.AppendLine($"{baseIndent}    {{");
            sb.AppendLine($"{baseIndent}        {preserverName}Preserver();");
            sb.AppendLine($"{baseIndent}        {Tools.GetCondition()}");
            sb.AppendLine($"{baseIndent}        {{");

            var constructors = typeSymbol.InstanceConstructors
                .Where(c => c.DeclaredAccessibility == Accessibility.Public)
                .ToList();

            var contractInterfaces = typeSymbol.AllInterfaces
                .Where(it => it.ImplementsControllerContract())
                .ToList();

            var allMembers = typeSymbol.GetMembers()
                .Concat(typeSymbol.AllInterfaces.SelectMany(it => it.GetMembers()))
                .ToList();

            if (constructors.Count == 0)
            {
                GeneratePreservationBlock(sb, typeSymbol, baseIndent, fullProxyName, allMembers, contractInterfaces, null, 0);
            }
            else
            {
                for (int cIdx = 0; cIdx < constructors.Count; cIdx++)
                {
                    GeneratePreservationBlock(sb, typeSymbol, baseIndent, fullProxyName, allMembers, contractInterfaces,
                        constructors[cIdx], cIdx);
                }
            }

            sb.AppendLine($"{baseIndent}        }}");
            sb.AppendLine($"{baseIndent}    }}");
            sb.AppendLine($"{baseIndent}");
            sb.AppendLine(
                $"{baseIndent}    [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof({fullProxyName}))]");
            sb.AppendLine($"{baseIndent}    public static void {preserverName}Preserver() {{ }}");
            sb.AppendLine($"{baseIndent}}}");

            return sb.ToString();
        }

        private static void GeneratePreservationBlock(StringBuilder sb,
            INamedTypeSymbol typeSymbol,
            string baseIndent,
            string fullProxyName,
            List<ISymbol> allMembers,
            List<INamedTypeSymbol> contractInterfaces,
            IMethodSymbol constructor,
            int constructorIndex)
        {
            string ctorArgs = "";
            if (constructor != null)
            {
                ctorArgs = string.Join(", ", constructor.Parameters.Select(p =>
                    $"({p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})default!"));
            }

            var pVar = $"p_c{constructorIndex}";

            sb.AppendLine($"{baseIndent}            var {pVar} = new {fullProxyName}({ctorArgs});");

            ProcessMembersPreservation(sb, typeSymbol, baseIndent, allMembers, pVar, constructorIndex, "gen");

            int ifaceIndex = 0;
            foreach (var contractIface in contractInterfaces)
            {
                ifaceIndex++;
                var ifaceTypeFullName = contractIface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var contractIVar = $"c_i{constructorIndex}_f{ifaceIndex}";

                sb.AppendLine(
                    $"{baseIndent}            {ifaceTypeFullName} {contractIVar} = ({ifaceTypeFullName}){pVar};");

                var ifaceMembers = contractIface.GetMembers().ToList();
                ProcessMembersPreservation(sb, typeSymbol, baseIndent, ifaceMembers, contractIVar, constructorIndex,
                    $"iface{ifaceIndex}");
            }

            sb.AppendLine();
        }

        private static void ProcessMembersPreservation(StringBuilder sb,
            INamedTypeSymbol typeSymbol,
            string baseIndent,
            List<ISymbol> members,
            string targetVar,
            int constructorIndex,
            string suffix)
        {
            int methodIndex = 0;
            var attributes = new List<AttributeData>();

            foreach (var attr in typeSymbol.GetAttributes())
            {
                attributes.Add(attr);
            }
            
            foreach (var member in members)
            {
                var attributeArray = member.GetAllParameterAndPropertyAttributes();
                attributes.AddRange(attributeArray);
                
                if (member is IMethodSymbol method && method.MethodKind == MethodKind.Ordinary && method.DeclaredAccessibility == Accessibility.Public)
                {
                    methodIndex++;
                    var paramsList = string.Join(", ", method.Parameters.Select(p =>
                        $"({p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})default!"));

                    if (method.ReturnsVoid)
                    {
                        sb.AppendLine($"{baseIndent}            {targetVar}.{method.Name}({paramsList});");
                    }
                    else
                    {
                        var rI = $"r_c{constructorIndex}_m{methodIndex}_{suffix}";

                        var controllerMethod = typeSymbol.FindControllerImplementation(method);
                        if (controllerMethod!.DeclaredAccessibility == Accessibility.Private)
                        {
                            sb.AppendLine($"{baseIndent}            var {rI} = (({method.ContainingType.ToDisplayString()}){targetVar}).{method.Name}({paramsList});");
                        }
                        else
                        {
                            sb.AppendLine($"{baseIndent}            var {rI} = {targetVar}.{method.Name}({paramsList});");
                        }
                        sb.AppendLine($"{baseIndent}            _ = {rI}?.GetHashCode();");
                    }
                }
                else if (member is IPropertySymbol prop)
                {
                    sb.AppendLine($"{baseIndent}            _ = {targetVar}.{prop.Name}?.GetHashCode();");

                    if (!prop.IsReadOnly)
                    {
                        sb.AppendLine($"{baseIndent}            {targetVar}.{prop.Name} = default!;");
                    }
                }
            }
            
            var distinctAttributeTypes = attributes
                .Select(a => a.AttributeClass)
                .Where(c => c != null)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<ITypeSymbol>()
                .ToList();

            foreach (var attribute in distinctAttributeTypes)
            {
                if (attribute != null)
                {
                    var name = $"attr_{targetVar}_{attribute.GetSafeName()}";
                    
                    sb.AppendLine($"{baseIndent}            var {name} = typeof({typeSymbol.ToDisplayString()}).GetCustomAttribute<{attribute.ToDisplayString()}>();");
                    sb.AppendLine($"{baseIndent}            {name}?.GetHashCode();");
                }
            }
        }
    }
}