using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using Hubcon.Analyzers.SourceGenerators.Models;
using HubconAnalyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateEndpointParameterWrappers
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<ControllerMetadata> controllers,
            string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine("using System.Collections.Immutable;");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.Serialization;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc.ModelBinding;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");

            // ParameterWrapperProvider
            sb.AppendLine($"    public static class ParameterWrapperProvider");
            sb.AppendLine("    {");
            sb.AppendLine(
                "        #if UNITY_2017_1_OR_NEWER\r\n        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\r\n        #else\r\n        [ModuleInitializer]\r\n        #endif");
            sb.AppendLine("        public static void Init()");
            sb.AppendLine("        {");
            sb.AppendLine(
                "             global::Hubcon.EndpointManager.Setup(EndpointDelegateProvider.GetDelegate, EndpointInvokerProvider.GetInvoker, ParameterWrapperProvider.GetWrapperType, ParameterWrapperProvider.GetWrapperDelegate);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine(
                "        public static Type? GetWrapperType(string controller, string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine("            var finalSignature = controller + \"_\" + contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");

            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    if (endpoint.Parameters.Count(x =>
                            x.Type.ToDisplayString() != "System.Threading.CancellationToken") == 0) continue;

                    sb.AppendLine(
                        $"                 case \"{endpoint.Identifier}\": return typeof({endpoint.FullName}_Request);");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine(
                "        public static Func<IReadOnlyDictionary<string, object>, object>? GetWrapperDelegate(string controller, string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine(
                "            var finalSignature = controller + \"_\" + contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");

            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    if (endpoint.Parameters.Count(x =>
                            x.Type.ToDisplayString() != "System.Threading.CancellationToken") == 0) continue;

                    sb.AppendLine(
                        $"                 case \"{endpoint.Identifier}\": return {endpoint.FullName}_Request.GetWrapped;");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Wrapper classes
            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    var nonCancelParams = endpoint.Parameters
                        .Where(x => x.Type.ToDisplayString() != "System.Threading.CancellationToken")
                        .ToList();

                    if (nonCancelParams.Count == 0) continue;

                    var wrapperClassName = $"{endpoint.FullName}_Request";

                    sb.AppendLine($"    public sealed class {wrapperClassName} : global::Hubcon.IWrapper");
                    sb.AppendLine("    {");
                    sb.AppendLine(
                        $"        [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof({wrapperClassName}))]");
                    sb.AppendLine(
                        $"        [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors, typeof({wrapperClassName}))]");
                    sb.AppendLine($"        public {wrapperClassName}(){{  }}");

                    SymbolTools.MapPropertyAttributes(endpoint, wrapperClassName, sb, true);

                    // ValidatorNode
                    var emittedValidators = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
                    var visitedTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
                    
                    foreach (var param in nonCancelParams)
                        ValidatorTools.CollectAndEmitNestedValidators(sb, param.Type, "        ", visitedTypes, emittedValidators, true);

                    // ValidatorNode principal del wrapper
                    sb.AppendLine();
                    var mainValidatorExists = false;
                    if (nonCancelParams.Any(x => x.Attributes.Count > 0))
                    {
                        sb.AppendLine(
                            $"        private static readonly global::Hubcon.Validation.ValidatorNode<{wrapperClassName}> _validatorNode =");
                        sb.AppendLine(
                            $"            global::Hubcon.Validation.ValidatorNode<{wrapperClassName}>.Create()");

                        foreach (var param in nonCancelParams)
                        {
                            var attrs = param.Attributes.Where(ValidatorTools.IsValidationAttribute).ToArray();
                            
                            var inlineAttrs = ValidatorTools.GetInlineAttributes(attrs);
                            ValidatorTools.EmitBuilderEntry(sb, param.Name, param.Type,
                                inlineAttrs,
                                emittedValidators,
                                "                ");
                        }

                        sb.AppendLine("                .Build();");
                        mainValidatorExists = true;
                    }

                    // GetWrapped / Populate
                    sb.AppendLine();
                    sb.AppendLine(
                        $"        public static object GetWrapped(IReadOnlyDictionary<string, object> parameters_{endpoint.FullName})");
                    sb.AppendLine("        {");
                    sb.AppendLine($"             var wrapped = new {wrapperClassName}();");
                    foreach (var param in nonCancelParams)
                    {
                        string typeName = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        sb.AppendLine(
                            $"             wrapped.{param.Name} = parameters_{endpoint.FullName}.TryGetValue(\"{param.Name}\", out var {param.Name}_value) && {param.Name}_value != null ? ({typeName.Trim('?')}){param.Name}_value : {(typeName.EndsWith("?") ? "null" : "default!")};");
                    }

                    sb.AppendLine("             return wrapped;");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    sb.AppendLine(
                        $"        public void Populate(IReadOnlyDictionary<string, object> parameters_{endpoint.FullName})");
                    sb.AppendLine("        {");
                    foreach (var param in nonCancelParams)
                    {
                        string typeName = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        sb.AppendLine(
                            $"             {param.Name} = parameters_{endpoint.FullName}.TryGetValue(\"{param.Name}\", out var {param.Name}_value) && {param.Name}_value != null ? ({typeName.Trim('?')}){param.Name}_value : {(typeName.EndsWith("?") ? "null" : "default!")};");
                    }

                    sb.AppendLine("        }");

                    // BindAsync
                    sb.AppendLine();
                    sb.AppendLine(
                        $"        public static ValueTask<{wrapperClassName}> BindAsync(HttpContext context, System.Reflection.ParameterInfo parameter)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            return ValueTask.FromResult(new {wrapperClassName}());");
                    sb.AppendLine("        }");

                    // TryValidate
                    sb.AppendLine();

                    sb.AppendLine(
                        "        public bool TryValidate(out IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> errors)");
                    sb.AppendLine("        {");
                    
                    if (mainValidatorExists)
                    {
                        sb.AppendLine("            var results = new List<System.ComponentModel.DataAnnotations.ValidationResult>();");
                        sb.AppendLine("            var validationResult = _validatorNode.TryValidate(this, results);");
                        sb.AppendLine("            errors = results;");
                        sb.AppendLine("            return validationResult;");
                    }
                    else
                    {
                        sb.AppendLine("            errors = Array.Empty<System.ComponentModel.DataAnnotations.ValidationResult>();");
                        sb.AppendLine("            return true;");
                    }

                    sb.AppendLine("        }");

                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");
            spc.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}