using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using Hubcon.Shared.Abstractions.Standard.Interceptor;
using HubconAnalyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateProxyClass
    {
        public static void Execute(SourceProductionContext spc, INamedTypeSymbol iface, string fileName)
        {
            var proxyName = iface.Name + "Proxy";
            var namespaceName = iface.ContainingNamespace?.ToDisplayString();
            var sb = new StringBuilder();

            sb.AppendLine($"// Generated by Hubcon.Analyzers.SourceGenerators");
            sb.AppendLine($"");
            sb.AppendLine($"#nullable enable");
            sb.AppendLine($"using Hubcon;");
            sb.AppendLine($"using Hubcon.Shared.Abstractions.Standard.Interceptor;");
            sb.AppendLine($"using Hubcon.Shared.Abstractions.Standard.Interfaces;");
            sb.AppendLine($"using Hubcon.Shared.Core.Attributes;");
            sb.AppendLine($"using Hubcon.Client.Core.Proxies;");
            sb.AppendLine($"using System.Collections.Generic;");
            sb.AppendLine($"using System.Diagnostics.CodeAnalysis;");
            sb.AppendLine($"using System.Reflection;");
            sb.AppendLine($"using System.ComponentModel;");
            sb.AppendLine($"using System.Text.Json;");
            sb.AppendLine($"using System.Text.Json.Serialization;");
            sb.AppendLine($"using System.Text.Json.Serialization.Metadata;");
            sb.AppendLine($"using System.Runtime.CompilerServices;");
            sb.AppendLine($"");

            var hasNamespace = !string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>";
            var baseIndent = hasNamespace ? "    " : "";

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine($"{{");
            }

            sb.AppendLine($"{baseIndent}[HubconProxy]");
            sb.AppendLine($"{baseIndent}[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"{baseIndent}public class {proxyName} : BaseContractProxy, {iface.ToDisplayString()}");
            sb.AppendLine($"{baseIndent}{{");
            sb.AppendLine(
                $"{baseIndent}    [DynamicDependency(DynamicallyAccessedMemberTypes.PublicConstructors, typeof({proxyName}))]");
            sb.AppendLine($"{baseIndent}    public {proxyName}() {{ }}");
            sb.AppendLine();
            
            var props = iface.AllInterfaces
                .Prepend(iface)
                .SelectMany(i => i.GetMembers().OfType<IPropertySymbol>());

            foreach (var property in props)
            {
                var propertyName = property.Name;
                var propertyType = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                var fieldName = "_" + char.ToLower(propertyName[0]) + propertyName.Substring(1);

                sb.AppendLine($"{baseIndent}    private {propertyType} {fieldName};");

                sb.AppendLine($"{baseIndent}    public {propertyType} {propertyName}");
                sb.AppendLine($"{baseIndent}    {{");

                sb.AppendLine($"{baseIndent}        get => this.{fieldName};");

                if (property.SetMethod != null)
                {
                    sb.AppendLine($"{baseIndent}        set => this.{fieldName} = value;");
                }

                sb.AppendLine($"{baseIndent}    }}");
                sb.AppendLine();
            }

            var methods = iface.AllInterfaces
                .Prepend(iface)
                .SelectMany(i => i.GetMembers().OfType<IMethodSymbol>())
                .Where(m => !m.Name.StartsWith("get_") && !m.Name.StartsWith("set_"))
                .GroupBy(m => m.GetMethodSymbolSignature())
                .Select(g => g.First());

            foreach (var method in methods)
            {
                var stringMethodName = $"\"{method.GetMethodSymbolSignature()}\"";
                
                var returnType = method.ReturnType.ToDisplayString();
                var methodName = method.Name;
                var parameters = string.Join(", ",
                    method.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));

                sb.AppendLine($"{baseIndent}    public {returnType} {methodName}({parameters})");
                sb.AppendLine($"{baseIndent}    {{");

                var callMethod = "";


                var nonTokenParams = method.Parameters
                    .Where(p => !p.Type.Name.Equals("CancellationToken", StringComparison.OrdinalIgnoreCase))
                    .ToList();


                string AllParameters = ", null";

                if (nonTokenParams.Any())
                {
                    AllParameters = $", new Dictionary<string, object?>() {{ ";
                    bool first = true;

                    foreach (var param in nonTokenParams)
                    {
                        if (param.Type.Name.ToLower().Contains("cancellationtoken".ToLower()))
                            continue;

                        if (first)
                        {
                            AllParameters += $"{{ \"{param.Name}\", {param.Name} }}";
                            first = false;
                        }
                        else
                        {
                            AllParameters += $", {{ \"{param.Name}\", {param.Name} }}";
                        }
                    }

                    AllParameters += $" }}";
                }

                string cancellationTokenName = ", default";

                if (method.Parameters.Any(x => x.Type.Name.ToLower().Contains("CancellationToken".ToLower())))
                {
                    cancellationTokenName = ", " + method.Parameters
                        .First(x => x.Type.Name.ToLower().Contains("CancellationToken".ToLower())).Name;
                }

                if (returnType == "void")
                {
                    callMethod =
                        $"{nameof(BaseProxy.CallAsync)}({stringMethodName}{AllParameters}{cancellationTokenName}).Wait();";
                }
                else if (returnType.StartsWith("System.Collections.Generic.IAsyncEnumerable<"))
                {
                    var generic = returnType.GetGenericArgument("System.Collections.Generic.IAsyncEnumerable");
                    callMethod =
                        $"return {nameof(BaseProxy.StreamAsync)}<{generic}>({stringMethodName}{AllParameters}{cancellationTokenName});";
                }
                else if (method.Parameters.Any(p => p.Type.IsIAsyncEnumerable()))
                {
                    if (returnType.StartsWith("System.Threading.Tasks.Task<"))
                    {
                        var generic = returnType.GetGenericArgument("System.Threading.Tasks.Task");
                        callMethod =
                            $"return {nameof(BaseProxy.IngestAsync)}<{generic}>({stringMethodName}{AllParameters}{cancellationTokenName});";
                    }
                    else if (returnType == "System.Threading.Tasks.Task")
                    {
                        callMethod =
                            $"return {nameof(BaseProxy.IngestAsync)}({stringMethodName}{AllParameters}{cancellationTokenName});";
                    }
                    else
                    {
                        callMethod =
                            $"return {nameof(BaseProxy.IngestAsync)}<{returnType}>({stringMethodName}{AllParameters}{cancellationTokenName});";
                    }
                }
                else if (returnType.StartsWith("System.Threading.Tasks.Task<"))
                {
                    var generic = returnType.GetGenericArgument("System.Threading.Tasks.Task");
                    callMethod =
                        $"return {nameof(BaseProxy.InvokeAsync)}<{generic}>({stringMethodName}{AllParameters}{cancellationTokenName});";
                }
                else if (returnType == "System.Threading.Tasks.Task")
                {
                    callMethod =
                        $"return {nameof(BaseProxy.CallAsync)}({stringMethodName}{AllParameters}{cancellationTokenName});";
                }
                else
                {
                    callMethod =
                        $"return {nameof(BaseProxy.InvokeAsync)}<{returnType}>({stringMethodName}{AllParameters}{cancellationTokenName}).Result;";
                }

                sb.AppendLine($"{baseIndent}        {callMethod}");
                sb.AppendLine($"{baseIndent}    }}");
            }

            sb.AppendLine("");
            sb.AppendLine($"{baseIndent}    public override void SetPropertyValue(string propertyName, object value)");
            sb.AppendLine($"{baseIndent}    {{");
            sb.AppendLine($"{baseIndent}        switch (propertyName)");
            sb.AppendLine($"{baseIndent}        {{");

            foreach (var property in iface.GetMembers().OfType<IPropertySymbol>())
            {
                var propertyName = property.Name;
                var propertyType = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                var fieldName = "_" + char.ToLower(propertyName[0]) + propertyName.Substring(1);

                sb.AppendLine($"{baseIndent}            case \"{propertyName}\":");
                sb.AppendLine($"{baseIndent}                this.{fieldName} = value as {propertyType};");
                sb.AppendLine($"{baseIndent}                break;");
            }

            sb.AppendLine($"{baseIndent}        }}");
            sb.AppendLine($"{baseIndent}    }}");
            sb.AppendLine($"{baseIndent}}}");
            sb.AppendLine("");

            var preserver = GeneratePreserverClass.Execute(iface, "Proxy");
            sb.AppendLine(preserver);

            if (hasNamespace)
            {
                sb.AppendLine($"}}");
            }

            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
    }
}